Core_App/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (
    # core
    Home_View,
    Main_Home_View,

    # lorem
    Lorem_Ipsum_View,

    # errors
    Handle_404_Error_View,
)

app_name = 'Core_App'

urlpatterns = [
    # home page
    path('', Main_Home_View.as_view(), name='Main-Home-Page'),
    path('home/', Home_View.as_view(), name='Home-Page'),

    # erros
    path('404/', Handle_404_Error_View, name='404-Page'),


    # lorem ipsum
    path('lorem/', Lorem_Ipsum_View.as_view(), name='Lorem-Ipsum-Page'),
    path('ipsum/', Lorem_Ipsum_View.as_view()),
    path('loremipsum/', Lorem_Ipsum_View.as_view()),
    path('lorem-ipsum/', Lorem_Ipsum_View.as_view()),
]

Features_App/urls.py
from django.urls import path

from .views import (
    User_Info_View,
    Search_View,

    # compare
    Compare_Choice_View,
    Compare_Users_View,
    Compare_Tweets_View,

    # user-most-popular
    User_Most_Popular_Choice_View,
    User_Most_Popular_Followers_View,
    User_Most_Popular_Following_View,
)

app_name = 'Features_App'

urlpatterns = [
    path('user-info/', User_Info_View.as_view(), name='User-Info-Page'),
    path(
        'search/',
        Search_View.as_view(),
        name='Search-Page'
    ),

    # compare
    path('compare/', Compare_Choice_View.as_view(), name='Compare-Choice-Page'),
    path('compare/users/', Compare_Users_View.as_view(), name='Compare-Users-Page'),
    path(
        'compare/tweets/',
        Compare_Tweets_View.as_view(),
        name='Compare-Tweets-Page'
    ),

    # user-most-popular
    path(
        'user-most-popular/',
        User_Most_Popular_Choice_View.as_view(),
        name='User-Most-Popular-Choice-Page'
    ),
    path(
        'user-most-popular/followers/',
        User_Most_Popular_Followers_View.as_view(),
        name='User-Most-Popular-Followers-Page'
    ),
    path(
        'user-most-popular/following/',
        User_Most_Popular_Following_View.as_view(),
        name='User-Most-Popular-Following-Page'
    ),

]

twitter_tweepy_api/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin-panel/', admin.site.urls),

    # Core_App
    path('', include('Core_App.urls')),

    # Features_App
    path('', include('Features_App.urls')),
]

Core_App/views.py
from django.views.generic import TemplateView, RedirectView
from django.urls.base import reverse
from django.shortcuts import render


class Main_Home_View(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        # if self.request.user.is_authenticated:
        #     return reverse("Core_App:Home-Page")
        # else:
        #     return reverse("Core_App:Home-Page")

        return reverse("Core_App:Home-Page")


class Home_View(TemplateView):
    template_name = 'Core_App/Home_Template.html'


class Lorem_Ipsum_View(TemplateView):
    template_name = 'Core_App/Lorem_Ipsum_Template.html'


def Handle_404_Error_View(request, exception=None, *args, **kwargs):
    return render(request, 'Core_App/404_Error_Template.html')

templates/Core_App/404_Error_Template.html
{% extends 'Core_Base_Template.html' %} {% block Core_Content %}
<!---->
{% load static %}

<!-- Title -->
{% block title %}
<title>404 Error Page</title>
{% endblock title %}
<div class="container mb-5 mt-3 text-center">
	<img src="{% static 'images/Are_You_sure_about_that.gif' %}" alt="" />
	<h1>404</h1>
	<h1>Page Not Found</h1>
	<div class="mt-4">
		<a href="{% url 'Core_App:Main-Home-Page' %}">
			Go to Home Page
		</a>
	</div>
</div>

{% endblock Core_Content %}

templates/Core_App/Home_Template.html
{% extends 'Core_Base_Template.html' %}

<!-- Title -->
{% load static %} {% block title %}
<title>Home Page</title>
{% endblock title %} {% block Core_Content %}

<div class="container mt-3 mb-5 text-center">
	<h1 class="mb-4">Options</h1>
	<div class="col-md-6 mx-auto">
		<div class="d-flex flex-column gap-2">
			<a
				href="{% url 'Features_App:User-Info-Page' %}"
				class="p-2 btn btn-lg btn-success"
			>
				User Info
			</a>

			<a
				href="{% url 'Features_App:Search-Page' %}"
				class="p-2 btn btn-lg btn-success"
			>
				Search
			</a>

			<a
				href="{% url 'Features_App:Compare-Choice-Page' %}"
				class="p-2 btn btn-lg btn-success"
			>
				Compare
			</a>
			<a
				href="{% url 'Features_App:User-Most-Popular-Choice-Page' %}"
				class="p-2 btn btn-lg btn-success"
			>
				User Most Popular
			</a>
		</div>
	</div>
</div>

{% endblock Core_Content %}

templates/Core_App/Lorem_Ipsum_Template.html
{% extends 'Core_Base_Template.html' %} {% block Core_Content %}

<!-- Title -->
{% block title %}
<title>Lorem Ipusm Page</title>
{% endblock title %}

<div class="container my-3 mb-5">
	<h1 class="text-center mb-3">Lorem Ipsum</h1>

	<p style="text-align: justify">
		Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi
		animi reprehenderit laborum quis rerum minima pariatur ipsam nisi,
		voluptates iste! Molestiae dolores illum architecto, repellat, odio
		porro natus laborum iste nobis animi nemo autem, eos laboriosam quae
		voluptate blanditiis? Sed sit impedit debitis, non hic minima quis id a
		laboriosam dicta earum quas consequuntur illum quia beatae accusantium
		ex. Atque quod distinctio natus harum perferendis asperiores id ab,
		soluta quia ad quisquam exercitationem maiores voluptate alias nam,
		impedit veritatis aspernatur iste doloremque odio! Nam laudantium
		repudiandae natus ducimus eos reprehenderit, quasi saepe eaque ab quod,
		assumenda nesciunt ut atque consequatur. Mollitia, tenetur impedit!
		Cupiditate, mollitia eligendi fugit quisquam quis dolor quibusdam ad
		necessitatibus harum exercitationem vero, autem esse nisi? Nam fuga eius
		pariatur velit rem, totam cupiditate excepturi ullam sint beatae iure
		ipsam suscipit aut facilis molestias, perferendis quisquam explicabo
		placeat neque sunt voluptas impedit exercitationem. Et hic repellat,
		repellendus maiores facilis cupiditate, deserunt fuga nostrum qui nam
		aliquam vel, unde pariatur laborum sapiente accusantium! Mollitia,
		veniam culpa atque ratione, totam rerum dicta, tempora incidunt animi
		quod voluptate alias ullam quam magnam vitae! Officia mollitia vel est
		aliquid, eius, aut quibusdam quae repellendus fugit ipsum iusto neque
		porro incidunt facere repudiandae. Accusamus rerum debitis nesciunt.
		Veritatis porro quasi sequi incidunt accusamus ex, eius ducimus libero!
		Illo debitis sapiente voluptatum inventore nisi quidem obcaecati et,
		quibusdam praesentium atque asperiores fugiat illum neque doloribus
		cupiditate recusandae voluptate assumenda explicabo, deserunt velit
		voluptas. Modi libero ex consequatur incidunt veritatis dolor blanditiis
		eum saepe odit veniam atque, neque sed cum nam? Fugiat, quisquam in
		reprehenderit laudantium officiis accusamus quos quasi sunt nihil!
		Minima aut culpa dignissimos nam ducimus in eaque expedita
		necessitatibus? Repellat neque, aut nobis delectus et praesentium dolor
		alias voluptates sed deserunt dignissimos consequuntur perferendis ea
		corrupti, omnis modi laboriosam odio ab repellendus odit veritatis dicta
		voluptate deleniti. Perspiciatis quas quae vel? Fugit eligendi iusto
		commodi sequi nisi amet ipsum aliquid similique, optio est ullam
		corrupti cupiditate atque porro iste! Animi totam, soluta ducimus
		placeat delectus vitae esse beatae laboriosam magnam quaerat. Hic
		corporis ab est ex exercitationem vero fuga amet atque voluptatibus
		natus. Aut explicabo atque aliquam officiis itaque quia doloribus
		aliquid reiciendis nostrum, voluptate numquam odit id repellendus, minus
		consequuntur! Dignissimos architecto id excepturi natus doloremque ab
		illum commodi quidem delectus ipsum obcaecati nisi eos animi, est quo,
		praesentium quis ea vel, perspiciatis odio laborum iste. Corporis natus
		recusandae ut, aperiam incidunt sit laboriosam facere ab dignissimos,
		eligendi et, eos praesentium. Culpa nemo labore sequi ad in expedita
		nostrum eos repellendus numquam quibusdam laudantium aperiam porro,
		velit ea, molestias exercitationem omnis, magni dolor adipisci? Nam
		nobis aperiam repudiandae id odio quis saepe aut doloribus cum
		exercitationem laboriosam ipsam laudantium, doloremque eos, at magnam
		voluptatibus velit. Culpa voluptatum, rem, nam aliquam, repellat et
		inventore dolores magni dicta id tenetur illo aspernatur. Laborum
		consectetur quibusdam nihil atque laboriosam explicabo nulla eaque
		repellat ratione, eligendi sunt iure esse odio maiores rerum! Odio,
		reiciendis consectetur ipsum praesentium quae voluptatibus ea quaerat
		harum. A, enim sit qui explicabo id earum quas atque, blanditiis non
		modi deserunt deleniti officiis eaque illum sequi dolores ad quaerat
		esse tenetur animi hic optio laborum maxime. Exercitationem ea suscipit
		reiciendis incidunt quis saepe natus ratione veritatis sapiente aperiam
		omnis nihil sit placeat quibusdam minus corrupti repudiandae similique
		illum totam, fugiat aut magnam dolor, quaerat possimus. Eligendi hic,
		vitae, quod veniam enim aspernatur officia ratione minus aut dolor
		officiis. Maxime repellat velit ut animi esse, itaque autem maiores
		accusamus perferendis, eaque minima illo enim facilis veritatis
		perspiciatis facere laborum, inventore excepturi optio molestias quas
		necessitatibus sequi fugiat? Alias incidunt magnam, sapiente quod
		aliquam temporibus impedit quidem. Nisi fugit vel reprehenderit, quidem
		blanditiis minus ullam repellendus, non facilis minima quam ipsum harum
		consequatur aut modi in unde quis dicta hic cum. Ipsum magnam, nobis
		amet non placeat adipisci quasi sed cumque odit voluptatum aperiam fuga
		voluptas temporibus inventore quo quae soluta repudiandae eum accusamus
		sequi tempore. Alias cumque blanditiis expedita corporis temporibus,
		animi deleniti qui suscipit aliquam molestiae quasi officia ratione
		perferendis doloremque reprehenderit laboriosam sed odio eveniet beatae,
		iure fugiat? Incidunt, error nemo? Ratione repellendus vel ipsum vitae
		quaerat beatae aperiam. Maxime alias, sequi quod fugit cum ipsum unde at
		dolore modi quam fuga labore repellendus veniam laudantium amet minus
		velit iste necessitatibus, quia temporibus numquam vitae! Ullam iusto
		enim similique explicabo excepturi iste qui laboriosam animi expedita
		ratione aliquid, a doloremque, iure magnam? Aspernatur placeat rerum,
		magnam ex iste doloremque fugit commodi veniam molestias nemo eos eius
		quae suscipit! Temporibus harum atque ratione doloremque fugiat sunt
		cupiditate velit totam nisi tenetur consequatur, non omnis pariatur
		voluptate nulla incidunt voluptas. Enim amet, reiciendis aperiam illum
		rem dignissimos. Optio maiores, porro repellat velit commodi corrupti
		nobis beatae ipsa voluptate cumque vitae dignissimos magnam architecto
		excepturi sed. Deleniti earum minima nisi necessitatibus. In sint culpa
		voluptatem, deleniti temporibus cupiditate, ipsa quidem debitis eveniet
		unde veniam voluptatibus voluptatum similique hic explicabo aut?
		Reprehenderit molestias temporibus aspernatur consectetur placeat sunt
		iste vitae veritatis perferendis expedita ipsam mollitia eligendi enim,
		tempore odit. Suscipit debitis in facilis ut quibusdam neque nostrum
		quidem amet deleniti, voluptates excepturi. Reprehenderit tenetur
		ducimus eligendi deserunt porro autem, vero rerum quod molestias
		dignissimos nostrum consequatur omnis saepe soluta placeat a ea unde et
		itaque repellat corporis odio illum. Accusantium, quae doloremque?
		Ratione molestiae provident tempore aliquid veniam. Quos iusto itaque
		quas, quasi nam error maxime alias placeat doloribus, quia commodi ab
		voluptas nemo dolorum in temporibus magnam accusamus cum quibusdam dolor
		animi expedita? Corrupti rerum, ea dolores libero alias, unde recusandae
		nobis exercitationem, accusamus quae laborum reiciendis nemo omnis velit
		quis minus inventore? Repudiandae, ipsa assumenda ex ad harum
		consectetur, ea provident modi accusamus, nemo voluptatum. Aliquid error
		ullam veniam ad, neque eum iusto, similique exercitationem asperiores,
		hic harum id eos nostrum consequuntur. Fuga saepe, voluptatem aperiam
		praesentium numquam voluptatum quidem blanditiis impedit corporis porro
		fugiat, asperiores nostrum, repudiandae repellendus odio beatae laborum
		minima aut sunt aspernatur! Recusandae, suscipit sapiente laborum
		inventore fugit, eligendi ut quaerat assumenda provident quos
		perferendis, sunt illum.
	</p>
</div>

{% endblock Core_Content %}