Core_App/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (
    # core
    Home_View,
    Main_Home_View,

    # lorem
    Lorem_Ipsum_View,

    # errors
    Handle_404_Error_View,
)

app_name = 'Core_App'

urlpatterns = [
    # home page
    path('', Main_Home_View.as_view(), name='Main-Home-Page'),
    path('home/', Home_View.as_view(), name='Home-Page'),

    # erros
    path('404/', Handle_404_Error_View, name='404-Page'),


    # lorem ipsum
    path('lorem/', Lorem_Ipsum_View.as_view(), name='Lorem-Ipsum-Page'),
    path('ipsum/', Lorem_Ipsum_View.as_view()),
    path('loremipsum/', Lorem_Ipsum_View.as_view()),
    path('lorem-ipsum/', Lorem_Ipsum_View.as_view()),
]

Features_App/urls.py
from django.urls import path

from .views import (
    User_Info_View,
    Search_View,

    # compare
    Compare_Choice_View,
    Compare_Users_View,
    Compare_Tweets_View,

    # user-most-popular
    User_Most_Popular_Choice_View,
    User_Most_Popular_Followers_View,
    User_Most_Popular_Following_View,
)

app_name = 'Features_App'

urlpatterns = [
    path('user-info/', User_Info_View.as_view(), name='User-Info-Page'),
    path(
        'search/',
        Search_View.as_view(),
        name='Search-Page'
    ),

    # compare
    path('compare/', Compare_Choice_View.as_view(), name='Compare-Choice-Page'),
    path('compare/users/', Compare_Users_View.as_view(), name='Compare-Users-Page'),
    path(
        'compare/tweets/',
        Compare_Tweets_View.as_view(),
        name='Compare-Tweets-Page'
    ),

    # user-most-popular
    path(
        'user-most-popular/',
        User_Most_Popular_Choice_View.as_view(),
        name='User-Most-Popular-Choice-Page'
    ),
    path(
        'user-most-popular/followers/',
        User_Most_Popular_Followers_View.as_view(),
        name='User-Most-Popular-Followers-Page'
    ),
    path(
        'user-most-popular/following/',
        User_Most_Popular_Following_View.as_view(),
        name='User-Most-Popular-Following-Page'
    ),

]

twitter_tweepy_api/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin-panel/', admin.site.urls),

    # Core_App
    path('', include('Core_App.urls')),

    # Features_App
    path('', include('Features_App.urls')),
]

templates/Base_Template.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />

		<!-- Title -->
		{% block title %}
		<title>Twitter Tweepy API</title>
		{% endblock title %}

		<!-- stylesheets -->
		{% block stylesheets %}
		<!-- Bootstrap CSS -->
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
			crossorigin="anonymous"
		/>
		{% endblock stylesheets %}

		<!-- icons -->
		{% block icons %}
		<link
			rel="shortcut icon"
			href="{% static 'images/logo3.svg' %}"
			type="image/x-icon"
		/>
		{% endblock icons %}
	</head>
	<body>
		<!-- Base_Content -->
		{% block Base_Content %} Shows me if you can {% endblock Base_Content %}

		<!-- scripts -->
		{% block scripts %}
		<!-- Bootstrap JS -->
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
			crossorigin="anonymous"
		></script>
		{% endblock scripts %}
	</body>
</html>

templates/Core_Base_Template.html
{% extends 'Base_Template.html' %} {% block Base_Content %}

<!-- navbar -->
{% include 'Navbar.html' %}

<!-- Message container -->
{% if messages %}
<div class="container">
	{% for message in messages %}

	<div
		class="alert alert-{{ message.tags }} alert-dismissible fade show mt-3"
		role="alert"
	>
		{{ message|safe }}
		<div style="">
			<button
				type="button"
				class="btn-close"
				data-bs-dismiss="alert"
				aria-label="Close"
			></button>
		</div>
	</div>

	{% endfor %}
</div>

{% endif %}

<!-- Core_Content -->
{% block Core_Content %}{% endblock Core_Content %} {% endblock Base_Content %}

templates/Home_Template.html
{% extends 'Core_Base_Template.html' %}

<!-- Title -->
{% load static %} {% block title %}
<title>Home Page</title>
{% endblock title %} {% block Core_Content %}

<div class="container mt-3 mb-5 text-center">
	<h1>This is Home Page</h1>
	<div>
		Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi, dolorum.
		Possimus dolore sunt magnam delectus voluptas officia dolorem ipsa
		suscipit laudantium soluta quis natus excepturi expedita doloremque,
		voluptatum et temporibus!
	</div>
</div>

{% endblock Core_Content %}

templates/Navbar.html
{% load static %}
<nav
	class="
		navbar navbar-expand-md navbar-dark
		bg-dark
		sticky-top
		justify-content-between
	"
>
	<div class="container">
		<a class="navbar-brand" href="{% url 'Core_App:Main-Home-Page' %}">
			<img
				src="{% static 'images/logo3.svg' %}"
				style="border-radius: 20%; height: 40px"
				class="img-fluid"
			/>
		</a>
		<a href="{% url 'Core_App:Main-Home-Page' %}" class="navbar-brand fs-3">
			Twitter Bot
		</a>

		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarNavAltMarkup"
			aria-controls="navbarNavAltMarkup"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
			<!-- Solution left right is :- me-auto mb-lg-0 -->

			<!-- Left side Nav-Link -->
			<div class="navbar-nav me-auto mb-lg-0">
				<a href="{% url 'Core_App:Home-Page' %}" class="nav-link">
					Home
				</a>

				<a
					href="{% url 'Features_App:User-Info-Page' %}"
					class="nav-link"
				>
					User-Info
				</a>

				<a href="{% url 'Features_App:Search-Page' %}" class="nav-link">
					Search
				</a>

				<li class="nav-item dropdown">
					<a
						class="nav-link dropdown-toggle"
						href="#"
						id="choiceCompare"
						role="button"
						data-bs-toggle="dropdown"
						aria-expanded="false"
					>
						Compare
					</a>
					<ul class="dropdown-menu" aria-labelledby="choiceCompare">
						<a
							class="dropdown-item"
							href="{% url 'Features_App:Compare-Users-Page' %}"
						>
							Users
						</a>
						<a
							class="dropdown-item"
							href="{% url 'Features_App:Compare-Tweets-Page' %}"
						>
							Tweets
						</a>
					</ul>
				</li>

				<li class="nav-item dropdown">
					<a
						class="nav-link dropdown-toggle"
						href="#"
						id="choiceCompare"
						role="button"
						data-bs-toggle="dropdown"
						aria-expanded="false"
					>
						User-Most-Popular
					</a>
					<ul class="dropdown-menu" aria-labelledby="choiceCompare">
						<a
							href="{% url 'Features_App:User-Most-Popular-Followers-Page' %}"
							class="dropdown-item"
						>
							Followers
						</a>

						<a
							href="{% url 'Features_App:User-Most-Popular-Following-Page' %}"
							class="dropdown-item"
						>
							Following
						</a>
					</ul>
				</li>
			</div>
		</div>
	</div>
</nav>